# SPDX-License-Identifier: Apache-2.0

name: Rule Executer - Rule processor Automation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  automate-rule-executer:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN_LIB }}

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up NPM authentication
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN_LIB }}" > ~/.npmrc
          cat .npmrc

      # Verify Changes in modified files
      - name: Verify Changes
        run: |
          cat package.json
          cat Dockerfile

      # Step 5: Build Rule Packages
      - name: Build Rule Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_LIB }}
        run: |
          echo "Building rule 901 package..."
          npm install
          echo "Rule packages built."

      # Step 6: Build and Push Docker Image
      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "Packaging rule processors into Docker image..."
          docker build -t tazamaorg/rule-901:2.1.0
          echo "Logging into DockerHub..."
          echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
          docker push tazamaorg/rule-901:2.1.0
          docker rmi tazamaorg/rule-901:2.1.0
          echo "Docker Image creation and push complete."

      # Step 6: Send Slack Notification
      - name: Send Slack Notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"blocks": [{"type": "header","text": {"type": "plain_text","text": "New Rule Dockerhub Image published :ship:","emoji": true}},{"type": "section","fields": [{"type": "mrkdwn","text": "*Service:*\nRule-901"},{"type": "mrkdwn","text": "*Tazama Dockerhub:*\n<https://hub.docker.com/orgs/tazamaorg/repositories>"}]}]}' $SLACK_WEBHOOK_URL
